### ISSUE TITLE
pg_qualstats_index_advisor functionality

### ISSUE THREAD

**Issue by romanstingler** [powa-team/pg_qualstats#53] opened 2022-08-23 07:44 UTC
I installed the latest revision 66b3037 on my local PG 14.5 machine.
I found that you added the "docs" for the advisor here
https://github.com/powa-team/pg_qualstats/issues/31

Your code example:
```
SELECT v
  FROM json_array_elements(
    pg_qualstats_index_advisor(min_filter => 50)->'indexes') v
  ORDER BY v::text COLLATE "C";
  ``` 
  fails with **SQL Error [22023]: ERROR: cannot call json_array_elements on a scalar**

but all I can figure out is: 

`SELECT pg_qualstats_index_advisor();`
```
{
  "indexes": null,
  "unoptimised": [
    {
      "qual": "assemblies.\"orderReferenceNumber\" ~~* ?",
      "queryids": [
        -6084300706674462045,
        -5817621241163067326
      ]
    },
    {
      "qual": "orders.\"orderReferenceNumber\" ~~* ?",
      "queryids": [
        5707918505950049101,
        9082355525220716366
      ]
    }
  ]
}
```

taking the first query :
`select pg_qualstats_example_query(-6084300706674462045);`

```
select
	*
from
	"assemblies"
where
	("assemblies"."orderInternalId"::text ilike $1
		or "assemblies"."orderReferenceNumber"::text ilike $2)
order by
	"assemblies"."id" desc,
	"orderType" asc
limit 10 offset 0
```
I have a BTREE index for both fields (orderInternalId,orderReferenceNumber).

If I remove one of the indexes and rerun the query again and check again 

`SELECT pg_qualstats_index_advisor();`
I get the same result as before, just with 1 more queryId.

I have a very busy schedule and just skimmed the code 
it seems that 
**v_ddl** is the part from your code example output and this is not returned. 
As soon as I have some time, I will have a closer look at the function.

**Comment by rjuju** [comment] 2022-08-23 08:15
Hi,

The error is because the "indexes" field is "null" and not an empty array or an array containing null.  I'm not sure how it can happen as the underlying variable is initialized with an empty array and skip null or empty "v_ddl".  Even if the generated index DDL was null, it should still yield an array, like:

```
rjuju=# select json_build_object('a', array_append('{}'::text[], null));
 json_build_object
-------------------
 {"a" : [null]}
(1 row)
```

For the unoptimized quals, that's expected.  The ILIKE (~~*) operator can't be automatically handled, as the index you shoud create depends on what values are used, and where are the placeholders (%) if any.

**Comment by romanstingler** [comment] 2022-08-23 08:41
thx, 

i tried to change the line to 

` v_indexes json[]= '{}';`

Works, but I have to check why my index is empty.


When I reset the qualstats:
`select  pg_qualstats_reset();`
and then 
`select pg_qualstats_index_advisor();`
```
{
  "indexes": [
    []
  ],
  "unoptimised": null
}
```

Then I remove the index on the created_at
```
explain
SELECT *
FROM "work_orders"
WHERE "work_orders"."created_at" >= '2002-08-23 00:00:00'
  and "work_orders"."created_at" <= '2022-08-24 23:59:59';
```
the query plan gives me
```
Seq Scan on work_orders  (cost=0.00..1.04 rows=3 width=160)
  Filter: ((created_at >= '2002-08-23 00:00:00'::timestamp without time zone) AND (created_at <= '2022-08-24 23:59:59'::timestamp without time zone))
  ```
  When I execute the query
  
  
  I get 2 entries in the output of 
  `select  pg_qualstats();`
  ```(10,16384,3050129,17,2065,,,1012069729,2475159725,763865873,2803659205,1,3,0,0,0,0,0,0,0,0,0,64,-715090605387815437,"'2002-08-23 00:00:00'::timestamp without time zone",f)```
  
but the advisor gives me: 
```
{
  "indexes": null,
  "unoptimised": null
}
```

**Comment by rjuju** [comment] 2022-08-23 09:20
> i tried to change the line to
> `v_indexes json[]= '{}';`

It shouldn't be necessary.  I tried locally on the same version (2.0.4), and it's working as expected:

```
CREATE TABLE t1(id integer, val text);
INSERT INTO t1 SELECT i, 'line ' || i FROM generate_series(1, 1000000) i;
SELECT * FROM t1 WHERE val ILIKE 'meh';
SELECT * FROM pg_qualstats_index_advisor(min_filter => 50);
             pg_qualstats_index_advisor
----------------------------------------------------
 {"indexes" : [], "unoptimised" : ["t1.val ~~* ?"]}
(1 row)
```

Simulating your use case:

```
CREATE TABLE push_job_logs(id integer, updated_at timestamp);
INSERT INTO push_job_logs select i, '2022-01-01'::timestamp + interval '1 day' * i from generate_series(1, 100000) i;
SELECT * FROM push_job_logs where updated_at >= '2022-02-01' AND updated_at <= '2022-02-02';
 id |     updated_at
----+---------------------
 31 | 2022-02-01 00:00:00
 32 | 2022-02-02 00:00:00
(2 rows)

SELECT * FROM pg_qualstats_index_advisor(min_filter => 50);
                                                                            pg_qualstats_index_advisor
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 {"indexes" : ["CREATE INDEX ON public.push_job_logs USING btree (updated_at)","CREATE INDEX ON public.push_job_logs USING btree (updated_at)"], "unoptimised" : ["t1.val ~~* ?"]}
(1 row)
```

(clearly the redundant indexes should be removed, but still it's giving sensible results)

There's definitely something unexpected on your environment, but I don't know what.

Can you try to call pg_qualstats_reset(), set pg_qualstats.sample_rate to 1 and try again the push_job_logs test case?  Maybe some of the stored quals are responsible for your problems.

**Comment by romanstingler** [comment] 2022-08-23 09:49
Could it be that the issue is the configuration

I changed from the defaults mentioned in the docs

```
pg_qualstats.enabled = true
pg_qualstats.track_constants = true
pg_qualstats.max = 1000
pg_qualstats.resolve_oids = false
pg_qualstats.track_pg_catalog = false
pg_qualstats.sample_rate = 1
```

to

```
pg_qualstats.resolve_oids = true
pg_qualstats.track_pg_catalog = true
```
maybe 
**pg_qualstats.track_pg_catalog** is mandatory. 
Now when I delete the index 
I get 

```
{
  "ddl": "CREATE INDEX ON public.push_job_logs USING btree (updated_at)",
  "queryids": [
    4635862364285714673
  ]
}
```

For me, it still fails if I reset the stats and execute your code example
I will keep this as this works perfectly fine 
```
    v_processed bigint[] = '{}';
    v_indexes json[] = '{}';
    v_unoptimised json[] = '{}';
```

Thx for the fast help

**Comment by rjuju** [comment] 2022-08-23 11:08
> pg_qualstats.resolve_oids = true
> pg_qualstats.track_pg_catalog = true

those shouldn't have an impact.

> Now when I delete the index
> I get
> 
> {
>   "ddl": "CREATE INDEX ON public.push_job_logs USING btree (updated_at)",
>   "queryids": [
>     4635862364285714673
>   ]
> }

This output comes from https://github.com/powa-team/pg_qualstats/commit/d203b05c4e53012d599191e702d7c8d6fe3c8222, so this is not the version 2.0.4 but the currently dev version 2.1.0.

It's unclear to me why you need to change the type of the arrays.  Did you create any extra extension, or custom cast or something?  Can you produce a script that creates a new database, create the pg_qualstats extension, some tables, add some data and reproduces the problem that I could try locally?

**Comment by romanstingler** [comment] 2022-08-23 13:42
The issue is if you don't pass a default value to the declaration it is initialized with NULL.

https://dbfiddle.uk/?rdbms=postgres_14&fiddle=b3f6ef8f178b471b5c9a78e0dd47c7c0

**Comment by romanstingler** [comment] 2022-08-23 14:13
sorry for distracting with the 2.0.4 version number 

but I use the code from the latest commit.

in 
https://github.com/powa-team/pg_qualstats/blob/master/pg_qualstats--2.1.0.sql

in line 451
```
    v_indexes json[];
    v_unoptimised json[];
```

**Comment by rjuju** [comment] 2022-08-23 14:20
Ahhh, that explains everything!  Thanks a lot for the report.  I apparently broke that in https://github.com/powa-team/pg_qualstats/commit/72e84f1f451b7cb2818c64177970babc6918d5be.   I will fix that shortly, and add some regression tests to make sure it doesn't get broken again.

**Comment by romanstingler** [comment] 2022-08-23 14:24
THX for your patience :)

**Comment by rjuju** [comment] 2022-08-23 14:36
This should be fixed as of https://github.com/powa-team/pg_qualstats/commit/c0b6ca06db307ed9ddd53b3facb0bc0c22b655b3.

Thanks again!

**Comment by romanstingler** [comment] 2022-08-23 14:52
Works perfectly now.

**Comment by rjuju** [comment] 2022-08-23 15:07
Great news!  I'm closing the issue, feel free to reopen it or create a new one if needed.

**Closed by rjuju** 2022-08-23 15:07 UTC
Labels: bug
