### ISSUE TITLE
cppcheck find bug

### ISSUE THREAD

**Issue by RekGRpth** [powa-team/pg_qualstats#44] opened 2021-11-10 10:40 UTC
```sh
pg_qualstats.c:741:15: style: Variable 'queryEntry' is assigned a value that is never used. [unreadVariable]
   queryEntry = (pgqsQueryStringEntry *) hash_search_with_hash_value(pgqs_query_examples_hash, &queryKey,
              ^
```

**Comment by rjuju** [comment] 2021-11-10 12:09
This is not a bug.

What cppcheck complains about is that indeed this assignment isn't necessary, but it's entirely harmless.  Performance wise it won't matter, and if it did it's quite likely that any recent compiler would optimize it.

Anyway thanks for the report, I will change it it as the real benefit from that will be to reduce the width of this block.

**Comment by rjuju** [comment] 2021-11-10 13:42
Fixed with a lot of additional similar changes in https://github.com/powa-team/pg_qualstats/commit/36588438773168f9d3a2c1096e092e65500e63c5!

**Closed by rjuju** 2021-11-10 13:42 UTC
Labels: enhancement
